var lang = {
    baseAttack: 'base attack',
    ability: 'ability',
    size: 'size',
    enhancement: 'enhancement',
    haste: 'haste',
    flanking: 'flanking',
    powerAttack: 'power attack',
    str: 'strength',
    dex: 'dexterity',
    wis: 'wisdom',
    powerAttackBonus: 'power attack',
    dice: 'dice',
    focus: 'focus',
    specialization: 'specialization',
    masterwork: 'masterwork',
    pointBlankShot: 'point blank shot',
    rapidShot: 'rapid shot',
    twoWeaponFighting: 'two weapon fighting'
}